/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.ConexaoBD;
import dao.ProdutoValidadeDAO;
import entidade.ProdutoValidade;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pretto
 */
public class IfrProdutoValidade extends javax.swing.JInternalFrame {

    int idProdutoValidade = 0;

    /**
     * Creates new form IfrCidade
     */
    public IfrProdutoValidade() {
        initComponents();

        new ProdutoValidadeDAO().popularTabela(tblProdutoValidade, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutoValidade = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfdConsultarProduto = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNomeProduto = new javax.swing.JTextField();
        tfdHoraCadastro = new javax.swing.JFormattedTextField();
        tfdDataCadastro = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdDataCompra = new javax.swing.JFormattedTextField();
        tfdHoraCompra = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdDataFabricacao = new javax.swing.JFormattedTextField();
        tfdHoraFabricacao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdDataVencimento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdObservacoes = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Cadastro: Cidade");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblProdutoValidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdutoValidade);

        jLabel2.setText("Busca");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfdConsultarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jLabel1.setText("Nome");

        try {
            tfdHoraCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdHoraCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdHoraCadastroActionPerformed(evt);
            }
        });

        try {
            tfdDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Dth Cadastro");

        jLabel4.setText("Dth Compra");

        try {
            tfdDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdDataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDataCompraActionPerformed(evt);
            }
        });

        try {
            tfdHoraCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdHoraCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdHoraCompraActionPerformed(evt);
            }
        });

        jLabel5.setText("Dth Fabricacao");

        try {
            tfdDataFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdDataFabricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDataFabricacaoActionPerformed(evt);
            }
        });

        try {
            tfdHoraFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Dth Vencimento");

        try {
            tfdDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDataVencimentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Observações");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfdNomeProduto)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfdDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfdDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdHoraCompra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfdDataFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(11, 11, 11)
                                .addComponent(tfdHoraFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfdDataVencimento)))
                    .addComponent(tfdObservacoes))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfdHoraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfdDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdHoraFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfdDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdHoraCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 370, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new ProdutoValidadeDAO().popularTabela(tblProdutoValidade, tfdConsultarProduto.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.atualizar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tfdDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDataVencimentoActionPerformed

    private void tfdDataFabricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDataFabricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDataFabricacaoActionPerformed

    private void tfdDataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDataCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDataCompraActionPerformed

    private void tfdHoraCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdHoraCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdHoraCadastroActionPerformed

    private void tfdHoraCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdHoraCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdHoraCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblProdutoValidade;
    private javax.swing.JTextField tfdConsultarProduto;
    private javax.swing.JFormattedTextField tfdDataCadastro;
    private javax.swing.JFormattedTextField tfdDataCompra;
    private javax.swing.JFormattedTextField tfdDataFabricacao;
    private javax.swing.JFormattedTextField tfdDataVencimento;
    private javax.swing.JFormattedTextField tfdHoraCadastro;
    private javax.swing.JFormattedTextField tfdHoraCompra;
    private javax.swing.JFormattedTextField tfdHoraFabricacao;
    private javax.swing.JTextField tfdNomeProduto;
    private javax.swing.JTextField tfdObservacoes;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        String nomeProduto = tfdNomeProduto.getText();

        String dataCadastro = tfdDataCadastro.getText();
        String horaCadastro = tfdHoraCadastro.getText();
        String dthCadastro = dataCadastro + " " + horaCadastro;

        String dataCompra = tfdDataCompra.getText();
        String horaCompra = tfdHoraCompra.getText();
        String dthCompra = dataCompra + " " + horaCompra;

        String dataFabricacao = tfdDataFabricacao.getText();
        String horaFabricacao = tfdHoraFabricacao.getText();
        String dthFabricacao = dataFabricacao + " " + horaFabricacao;

        String dataVencimento = tfdDataVencimento.getText();

        String observacao = tfdObservacoes.getText();

        // cricao obj ProdutoValidade
        ProdutoValidade produtoValidade = new ProdutoValidade(nomeProduto, dthCadastro, dthCompra, dthFabricacao, dataVencimento, observacao);

        // criacao do obj ProdutoValidadeDAO
        ProdutoValidadeDAO produtoValidadeDAO = new ProdutoValidadeDAO();

        if (idProdutoValidade == 0) { // representa uma INSERCAO
            if (produtoValidadeDAO.salvar(produtoValidade) == null) {
                tfdNomeProduto.setText("");
                tfdDataCadastro.setText("");
                tfdHoraCadastro.setText("");
                tfdDataCompra.setText("");
                tfdHoraCompra.setText("");
                tfdDataFabricacao.setText("");
                tfdHoraFabricacao.setText("");
                tfdDataVencimento.setText("");
                tfdObservacoes.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

                tfdNomeProduto.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        } else {
            produtoValidade.setId((long) idProdutoValidade);
            if (produtoValidadeDAO.atualizar(produtoValidade) == null) {
                tfdNomeProduto.setText("");
                tfdDataCadastro.setText("");
                tfdHoraCadastro.setText("");
                tfdDataCompra.setText("");
                tfdHoraCompra.setText("");
                tfdDataFabricacao.setText("");
                tfdHoraFabricacao.setText("");
                tfdDataVencimento.setText("");
                tfdObservacoes.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

                tfdNomeProduto.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        }

        idProdutoValidade = 0;
    }

    private void atualizar() {
        String idTabela = String.valueOf(tblProdutoValidade.getValueAt(tblProdutoValidade.getSelectedRow(), 0));

        idProdutoValidade = Integer.parseInt(idTabela);

        System.out.println(idProdutoValidade);
        
        ProdutoValidade produtoValidade = new ProdutoValidadeDAO().consultarId(idProdutoValidade);

        if (produtoValidade != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdNomeProduto.requestFocus();
            tfdNomeProduto.setText(produtoValidade.getNome());
            tfdDataCadastro.setText(produtoValidade.getDataHoraCadastro().split(" ")[0]);
            tfdHoraCadastro.setText(produtoValidade.getDataHoraCadastro().split(" ")[1]);
            tfdDataCompra.setText(produtoValidade.getDataHoraCompra().split(" ")[0]);
            tfdHoraCompra.setText(produtoValidade.getDataHoraCompra().split(" ")[1]);
            tfdDataFabricacao.setText(produtoValidade.getDataHoraFabricacao().split(" ")[0]);
            tfdHoraFabricacao.setText(produtoValidade.getDataHoraFabricacao().split(" ")[1]);
            tfdDataVencimento.setText(produtoValidade.getDataVencimento());
            tfdObservacoes.setText(produtoValidade.getObservacao());
        } else {
            JOptionPane.showMessageDialog(this, "Id do produto não encontrado!");
        }
    }
    
    private void excluir(){
        String idTabela = String.valueOf(tblProdutoValidade.getValueAt(tblProdutoValidade.getSelectedRow(), 0));

        idProdutoValidade = Integer.parseInt(idTabela);

        if (new ProdutoValidadeDAO().excluir(idProdutoValidade) == null) {
            JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");

            new ProdutoValidadeDAO().popularTabela(tblProdutoValidade, "");
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
        }

        idProdutoValidade = 0;
    }
}
