/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.busolli.lorenzo.vendaslorenzo.view;

import br.com.busolli.lorenzo.vendaslorenzo.DAO.CompraDAO;
import br.com.busolli.lorenzo.vendaslorenzo.DAO.FornecedorDAO;
import br.com.busolli.lorenzo.vendaslorenzo.apoio.CombosDAO;
import br.com.busolli.lorenzo.vendaslorenzo.apoio.Formatacao;
import br.com.busolli.lorenzo.vendaslorenzo.apoio.Validacao;
import br.com.busolli.lorenzo.vendaslorenzo.entidades.Compra;
import br.com.busolli.lorenzo.vendaslorenzo.entidades.Fornecedor;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author loren
 */
public class IfrCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrCidade
     */
    public IfrCompra() {
        initComponents();

        new CompraDAO().popularTabelaFornecedor(tblCompra, "");

        new CombosDAO().popularCombo("FORNECEDORES", jComboBox1);

        Formatacao.formatarData(tfdDataCompra);
        Formatacao.formatarData(tfdBuscaData);

    }

    int idCompra = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFecharManutCidades = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfdBuscaFornecedorCnpj = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tfdBuscaData = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvarCompra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tfdDataCompra = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setTitle("Cadastro: Compra");

        btnFecharManutCidades.setText("Fechar");
        btnFecharManutCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharManutCidadesActionPerformed(evt);
            }
        });

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompra);

        jLabel5.setText("Busca pela Data");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Busca pelo Fornecedor");

        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tfdBuscaData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdBuscaDataFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(tfdBuscaFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(tfdBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(tfdBuscaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfdBuscaFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jLabel1.setText("Data");

        btnSalvarCompra.setText("Salvar");
        btnSalvarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCompraActionPerformed(evt);
            }
        });

        jLabel2.setText("Fornecedor");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfdDataCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdDataCompraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 152, Short.MAX_VALUE)
                            .addComponent(tfdDataCompra))
                        .addGap(419, 419, 419))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btnSalvarCompra)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFecharManutCidades)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharManutCidades)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharManutCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharManutCidadesActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharManutCidadesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String criterio = tfdBuscaData.getText();
        new CompraDAO().popularTabelaData(tblCompra, criterio);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String criterio = tfdBuscaFornecedorCnpj.getText();
        new CompraDAO().popularTabelaFornecedor(tblCompra, criterio);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        String idTabela = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0));
        String data = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 1));
        String idFornecedor = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 2));

        idCompra = Integer.parseInt(idTabela);

        Compra compra = new CompraDAO().consultarId(idCompra);

        System.out.println(compra.getId());

        if (compra != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdDataCompra.setText(compra.getData());
            Integer inte = Integer.parseInt(compra.getForncedorId().toString());
            jComboBox1.setSelectedIndex(inte);

            tfdDataCompra.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da compra não encontrado!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String idTabela = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0));
        idCompra = Integer.parseInt(idTabela);
        CompraDAO compraDAO = new CompraDAO();

        try {

            compraDAO.excluir(idCompra);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Id da cidade não encontrado!");

        }

        compraDAO.popularTabelaFornecedor(tblCompra, "");

        idCompra = 0;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnSalvarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCompraActionPerformed
        //CADASTRAR

        String data = tfdDataCompra.getText();
        Integer idFornecedor = jComboBox1.getSelectedIndex();
        Long id = idFornecedor.longValue();

        Compra compra = new Compra(data, id);

        CompraDAO compraDAO = new CompraDAO();

        if (idCompra == 0) {

            if (compraDAO.salvar(compra) == null) {
                tfdDataCompra.setText("");
                jComboBox1.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

                tfdDataCompra.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }

            //EDITAR
        } else {

            Long idLong = (long) idCompra;
            compra.setId(idLong);

            if (compraDAO.atualizar(compra) == null) {

                tfdDataCompra.setText("");
                jComboBox1.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso!");

                tfdDataCompra.requestFocus();

            } else {

                JOptionPane.showMessageDialog(this, "Problemas ao atualizar registro!");

            }

        }

        compraDAO.popularTabelaFornecedor(tblCompra, "");

        idCompra = 0;

    }//GEN-LAST:event_btnSalvarCompraActionPerformed

    private void tfdDataCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdDataCompraFocusLost

        if (!tfdDataCompra.getText().contains(" ")) {

            if (!Validacao.validarDataFormatada(tfdDataCompra.getText())) {

                tfdDataCompra.setBackground(Color.YELLOW);

            } else {

                tfdDataCompra.setBackground(Color.WHITE);

            }

        } else {
            
            tfdDataCompra.setBackground(Color.YELLOW);
            
        }


    }//GEN-LAST:event_tfdDataCompraFocusLost

    private void tfdBuscaDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdBuscaDataFocusLost

        if (!tfdBuscaData.getText().contains(" ")) {

            if (!Validacao.validarDataFormatada(tfdBuscaData.getText())) {

                tfdBuscaData.setBackground(Color.YELLOW);

            } else {

                tfdBuscaData.setBackground(Color.WHITE);

            }

        } else {

            tfdBuscaData.setBackground(Color.YELLOW);

        }

    }//GEN-LAST:event_tfdBuscaDataFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharManutCidades;
    private javax.swing.JButton btnSalvarCompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCompra;
    private javax.swing.JFormattedTextField tfdBuscaData;
    private javax.swing.JTextField tfdBuscaFornecedorCnpj;
    private javax.swing.JFormattedTextField tfdDataCompra;
    // End of variables declaration//GEN-END:variables
}
